'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowUp, Download, Mail, MapPin, Menu, Smartphone, Layers3, Network, Code2, Check, Copy, ChevronLeft, ChevronRight, GraduationCap, Award, Users, BookOpen, ShieldCheck, Droplets, CookingPot, ExternalLink } from 'lucide-react';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { profile, projects, experience, skillGroups, education, awards, leadership, type Project } from '@/lib/portfolio';

function Github({size=18}:{size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/></svg> }
function Linkedin({size=18}:{size?:number}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4V9h4v2a4 4 0 0 1 2-3Z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg> }
const navigation = [{id:'home',label:'Home'},{id:'projects',label:'Projects'},{id:'experience',label:'Experience'},{id:'skills',label:'Skills'},{id:'about',label:'About'},{id:'contact',label:'Contact'}];

function ExternalAnchor({href,children,className='',label}:{href:string;children:React.ReactNode;className?:string;label?:string}) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className={className} aria-label={label}>{children}</a>;
}
function SocialLinks({labels=false}:{labels?:boolean}) {
  return <div className={`social-links ${labels?'with-labels':''}`}><ExternalAnchor href={profile.github} label="Rubaid on GitHub"><Github size={18}/>{labels&&'GitHub'}</ExternalAnchor><ExternalAnchor href={profile.linkedin} label="Rubaid on LinkedIn"><Linkedin size={18}/>{labels&&'LinkedIn'}</ExternalAnchor>{!labels&&<a href={`mailto:${profile.email}`} aria-label="Email Rubaid"><Mail size={18}/></a>}</div>;
}
function SectionHeader({number,label,title,subtitle}:{number:string;label:string;title:string;subtitle?:string}) {
  return <div className="section-header reveal"><div><p className="eyebrow"><span>{number}</span> / {label}</p><h2>{title}</h2></div>{subtitle&&<p className="section-intro">{subtitle}</p>}</div>;
}
function Navigation({active}:{active:string}) {
  const [open,setOpen]=useState(false);
  return <header className="site-header"><div className="nav-inner"><a href="#home" className="brand" aria-label="Rubaid — home">rubaid<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(n=><a href={`#${n.id}`} key={n.id} className={active===n.id?'active':''} aria-current={active===n.id?'location':undefined}>{n.label}</a>)}</nav><a href={profile.resume} className="nav-resume" download>Résumé <Download size={15}/></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu icon-button" aria-label="Open navigation"><Menu size={23}/></button></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle className="brand">rubaid<span>.</span></SheetTitle><SheetDescription>Flutter Developer · Dhaka, Bangladesh</SheetDescription><nav aria-label="Mobile navigation">{navigation.map((n,i)=><a href={`#${n.id}`} key={n.id} onClick={()=>setOpen(false)} aria-current={active===n.id?'location':undefined}><span>0{i+1}</span>{n.label}<ArrowUpRight size={21}/></a>)}</nav><a href={profile.resume} className="button secondary" download>Download résumé <Download size={17}/></a><SocialLinks labels/></SheetContent></Sheet></div></header>;
}
function Hero() {
  const heroRef=useRef<HTMLElement>(null);
  return <section id="home" className="hero" ref={heroRef} onPointerMove={(e)=>{if(e.pointerType!=='mouse'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();heroRef.current?.style.setProperty('--mouse-x',`${(e.clientX-r.left)/r.width*100}%`);}}><div className="hero-glow" aria-hidden="true"/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span className="short-line"/> FLUTTER DEVELOPER</p><h1>Mobile experiences.<br/>Built with <span className="gradient-text">Flutter.</span></h1><p className="hero-intro">I’m <strong>Rubaid Sharif Mahbub.</strong> I build polished Android and iOS apps, from responsive interfaces and API integration to release.</p><div className="hero-actions"><a className="button primary" href="#projects">View my work <ArrowDown size={18}/></a><a className="button secondary" href="#contact">Let’s talk <ArrowUpRight size={18}/></a></div><div className="hero-social"><SocialLinks/><span className="divider"/><a href={profile.resume} download className="text-link">Download résumé <Download size={15}/></a></div></div><div className="hero-portrait"><div className="portrait-outline" aria-hidden="true"/><div className="portrait-frame"><img src={profile.portrait} width={960} height={960} alt="Rubaid Sharif Mahbub wearing a navy blazer" fetchPriority="high"/><div className="portrait-caption"><span>Rubaid Sharif Mahbub</span><small>Flutter Developer · CSE, MIST</small></div></div><div className="portrait-tag"><Code2 size={20}/><span>One codebase.<br/><strong>Two platforms.</strong></span></div><span className="portrait-side">DESIGN TO DEVELOPMENT</span><div className="location-label"><MapPin size={15}/> Based in Dhaka, Bangladesh</div></div></div><div className="container hero-bottom"><span className="hero-bottom-note">MOBILE DEVELOPMENT, END TO END</span><div className="tech-strip"><span>Flutter</span><span>Dart</span><span>Firebase</span><span>REST APIs</span><span>Android & iOS</span></div><a href="#projects" className="scroll-cue" aria-label="Scroll to selected work"><ArrowDown size={17}/></a></div></section>;
}
function ProjectDetails({project,compact=false}:{project:Project;compact?:boolean}) {
  const [screen,setScreen]=useState(0);
  const images=project.screenshots;
  const previous=()=>setScreen(s=>(s-1+images.length)%images.length);
  const next=()=>setScreen(s=>(s+1)%images.length);
  return <Dialog onOpenChange={(open)=>{if(!open)setScreen(0)}}><DialogTrigger asChild><button className={compact?'project-open':'button project-button'} aria-label={`Explore ${project.name}`}>{compact?<ArrowUpRight size={23}/>:<>Explore project <ArrowUpRight size={17}/></>}</button></DialogTrigger><DialogContent className={`project-dialog ${images.length?'has-gallery':'no-gallery'}`}><div className="project-dialog-body"><div className="dialog-copy"><p className="eyebrow">{project.category}</p><DialogTitle className="dialog-title">{project.name}</DialogTitle><DialogDescription className="dialog-description">{project.description}</DialogDescription>{project.status&&<p className={`release-status ${project.id==='prochesta'?'published':''}`}>{project.id==='prochesta'&&<span/>}{project.status}</p>}{project.features.length>0&&<div className="detail-block"><h3>Inside the app</h3><ul>{project.features.map(f=><li key={f}><Check size={16}/><span>{f}</span></li>)}</ul></div>}<div className="detail-block"><h3>Technology & platforms</h3><div className="tags">{[...project.technologies,...project.platforms].map(t=><span key={t}>{t}</span>)}</div></div>{project.links.length>0&&<div className="detail-links">{project.links.map(l=><ExternalAnchor key={l.url} href={l.url} className="button secondary">{l.label}<ExternalLink size={16}/></ExternalAnchor>)}</div>}</div>{images.length>0&&<div className={`gallery ${project.color}`}><div className="gallery-top"><span>APP SCREENSHOTS</span><span aria-live="polite">{String(screen+1).padStart(2,'0')} / {String(images.length).padStart(2,'0')}</span></div><div className="gallery-stage"><button className="icon-button gallery-prev" onClick={previous} aria-label="Previous screenshot"><ChevronLeft size={22}/></button><img src={images[screen].src} alt={`${project.name} — ${images[screen].label}`} className="gallery-image" width={430} height={932}/><button className="icon-button gallery-next" onClick={next} aria-label="Next screenshot"><ChevronRight size={22}/></button></div><p className="gallery-caption" aria-live="polite">{images[screen].label}</p><div className="gallery-thumbs" aria-label="Choose a screenshot">{images.map((s,i)=><button key={s.src} className={screen===i?'selected':''} onClick={()=>setScreen(i)} aria-label={`Show ${s.label}`} aria-pressed={screen===i}><img src={s.src} alt="" width={40} height={84} loading="lazy"/></button>)}</div></div>}</div></DialogContent></Dialog>;
}
function ProjectShowcase({project,index}:{project:Project;index:number}) {
  return <article className={`project-showcase ${index%2?'reverse':''} ${project.color} reveal`}><div className="project-visual"><span className="visual-index">0{index+1} / {project.platforms.join(' + ')}</span><div className="device-composition"><div className="device secondary-device"><img src={project.screenshots[1].src} alt={`${project.name} ${project.screenshots[1].label}`} width={430} height={932} loading="lazy"/></div><div className="device primary-device"><img src={project.screenshots[0].src} alt={`${project.name} ${project.screenshots[0].label}`} width={430} height={932} loading="lazy"/></div></div><div className="visual-footnote"><span>{project.name}</span><span>BUILT WITH FLUTTER</span></div></div><div className="project-copy"><div className="project-identity"><div className={`app-logo ${project.id}`}><img src={project.logo} alt={`${project.name} logo`} width={44} height={44} loading="lazy"/></div><p className="eyebrow">{project.category}</p></div><h3>{project.name}</h3><p className="project-description">{project.description}</p><ul className="feature-list">{project.features.slice(0,2).map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><div className="project-tech">{project.technologies.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><p className={`release-status ${project.id==='prochesta'?'published':''}`}>{project.id==='prochesta'&&<span/>}{project.status}</p><div className="project-actions"><ProjectDetails project={project}/>{project.links.map(l=><ExternalAnchor href={l.url} key={l.url} className="text-link">{l.label}<ArrowUpRight size={16}/></ExternalAnchor>)}</div></div></article>;
}
function SelectedWork(){return <section id="projects" className="section selected-work"><div className="container"><SectionHeader number="01" label="SELECTED WORK" title="From code to real products." subtitle="A closer look at the mobile applications I’ve worked on."/><div className="project-list">{projects.filter(p=>p.featured).map((p,i)=><ProjectShowcase key={p.id} project={p} index={i}/>)}</div></div></section>}
function ExperienceTimeline(){return <section id="experience" className="section experience-section"><div className="container experience-layout"><div className="experience-intro reveal"><SectionHeader number="02" label="EXPERIENCE" title="Built through practice."/><p>Hands-on development, professional teams, and a growing focus on mobile products.</p><a href={profile.resume} className="text-link" download>View full résumé<ArrowUpRight size={17}/></a></div><div className="timeline">{experience.map((item,i)=><article className={`experience-item reveal ${i===0?'current':''}`} key={item.company}><div className="timeline-marker"/><div className="experience-meta"><p>{item.company}</p><span>{item.period}</span></div><h3>{item.roles[0].title}</h3>{item.roles.length>1&&<p className="current-role-date">{item.roles[0].date}</p>}<p className="experience-summary">{item.summary}</p>{item.roles.length>1&&<div className="role-progression">{item.roles.slice(1).map(role=><div key={role.title}><span>{role.title}</span><small>{role.date}</small></div>)}</div>}<div className="small-tech">{item.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>}
const skillIcons={mobile:Smartphone,layers:Layers3,network:Network,code:Code2};
function TechnicalExpertise(){return <section id="skills" className="section"><div className="container"><SectionHeader number="03" label="TECHNICAL EXPERTISE" title="The tools behind the work." subtitle="A Flutter-first stack, supported by thoughtful architecture and practical workflows."/><div className="skill-grid">{skillGroups.map((group,i)=>{const Icon=skillIcons[group.icon as keyof typeof skillIcons];return <article className="skill-group reveal" key={group.title}><div className="skill-top"><Icon size={25} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{group.title}</h3><p>{group.description}</p><div className="skill-list">{group.skills.map(s=><span key={s}>{s}</span>)}</div></article>})}</div><Accordion type="single" collapsible className="additional-skills reveal"><AccordionItem value="additional"><AccordionTrigger>Beyond mobile <span className="accordion-hint">Additional technologies & tools</span></AccordionTrigger><AccordionContent><div className="additional-tech-grid"><div><h4>Languages & web</h4><p>Python, JavaScript, React, MERN Stack, Java, C++, C#, C</p></div><div><h4>Databases</h4><p>MongoDB, MySQL, Oracle</p></div><div><h4>Tools & creative development</h4><p>IntelliJ IDEA, MATLAB, Unity, Unreal Engine, Blender, Adobe Illustrator</p></div></div></AccordionContent></AccordionItem></Accordion></div></section>}
function About(){return <section id="about" className="section about-section"><div className="container"><SectionHeader number="04" label="ABOUT" title="An engineer, with an eye for detail."/><div className="about-grid"><div className="about-photo reveal"><img src={profile.portrait} alt="Rubaid Sharif Mahbub" width={960} height={960} loading="lazy"/><div><MapPin size={15}/><span>Dhaka, Bangladesh</span></div></div><div className="about-copy reveal"><h3>Good mobile products start with care.</h3><p>My background is in Computer Science and Engineering at MIST. My work is in Flutter: translating designs into responsive interfaces and connecting them to the systems that make an app useful.</p><p>I’ve worked across exam preparation, education, and social applications. I enjoy the detail in that process — the interface, the data flow, and the final Android and iOS build.</p><div className="about-facts"><div><span>Education</span><strong>B.Sc. in CSE · MIST</strong></div><div><span>Languages</span><strong>Bangla <small>Native</small> · English <small>Fluent</small></strong></div></div></div></div><div className="more-projects"><div className="subsection-heading reveal"><h3>More to explore.</h3><p>Experiments in learning, everyday life, and connected devices.</p></div>{projects.filter(p=>!p.featured).map((p,i)=>{const Icon=[ShieldCheck,CookingPot,Droplets][i];return <article key={p.id} className="additional-project reveal"><div className="additional-project-icon"><Icon size={24} strokeWidth={1.5}/></div><div className="additional-project-copy"><h4>{p.name}<span>{p.category}</span></h4><p>{p.description}</p></div><div className="additional-project-tech">{p.technologies.slice(0,2).join(' · ')}</div><ProjectDetails project={p} compact/></article>})}</div></div></section>}
function Background(){return <section className="section background-section" aria-label="Education, awards, and leadership"><div className="container"><div className="background-top"><div className="education-block"><div className="subsection-heading reveal"><p className="eyebrow"><GraduationCap size={17}/> EDUCATION</p><h2>A strong foundation.</h2></div><article className="primary-education reveal"><p className="education-date">{education[0].date}</p><h3>{education[0].degree}</h3><p>{education[0].school}</p><span className="grade">{education[0].result}</span></article><Accordion type="single" collapsible className="earlier-education reveal"><AccordionItem value="earlier"><AccordionTrigger>Earlier education</AccordionTrigger><AccordionContent>{education.slice(1).map(e=><div className="earlier-education-item" key={e.degree}><h4>{e.degree}</h4><p>{e.school}</p><p>{e.date} · {e.result}</p></div>)}</AccordionContent></AccordionItem></Accordion><div className="certification reveal"><BookOpen size={19}/><div><span>CERTIFICATION</span><p>Python Fundamentals Certificate</p></div></div></div><div className="awards-block"><div className="subsection-heading reveal"><p className="eyebrow"><Award size={17}/> RECOGNITION</p><h2>Milestones along the way.</h2></div><div className="award-list">{awards.map(a=><article key={a.event} className="award-item reveal"><div className="award-symbol"><Award size={19} strokeWidth={1.5}/></div><div><h3>{a.place}</h3><p>{a.event}</p></div><span>{a.date}</span></article>)}</div></div></div><div className="leadership"><div className="subsection-heading reveal"><p className="eyebrow"><Users size={17}/> LEADERSHIP</p><h3>Growing with a community.</h3></div><div className="leadership-grid">{leadership.map((l,i)=><article className="leadership-item reveal" key={l.club}><div className="leadership-top"><span>0{i+1}</span><p>{l.date}</p></div><h4>{l.club}</h4><h5>{l.role}</h5><p>{l.description}</p></article>)}</div></div></div></section>}
function ContactSection(){const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);const copy=async()=>{let successful=false;const previous=document.activeElement as HTMLElement|null;const field=document.createElement('textarea');field.value=profile.email;field.setAttribute('readonly','');field.style.cssText='position:fixed;left:-9999px;top:0';document.body.appendChild(field);field.select();try{successful=document.execCommand('copy')}catch{}field.remove();previous?.focus({preventScroll:true});if(!successful&&navigator.clipboard){try{await Promise.race([navigator.clipboard.writeText(profile.email),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Clipboard unavailable')),1500))]);successful=true}catch{}}if(successful){setCopied(true);setCopyError(false);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),4000)}else{const text=document.querySelector('.contact-email>a>span');if(text){const range=document.createRange();range.selectNodeContents(text);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range)}setCopyError(true)}};return <section id="contact" className="section contact-section"><div className="container"><div className="contact-content reveal"><p className="eyebrow">05 / LET’S CONNECT</p><h2>Have a mobile product<br/>in mind<span>?</span></h2><p>I’d love to hear about Flutter opportunities, mobile projects, and thoughtful collaborations.</p><div className="contact-email"><a href={`mailto:${profile.email}`}><span>{profile.email}</span><ArrowUpRight size={31}/></a><button className="icon-button copy-email" onClick={copy} aria-label={copied?'Email copied':'Copy email address'}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><span className="copy-status" role="status">{copied?'Email copied':copyError?'Email selected. Use your device’s copy command.':''}</span><div className="contact-bottom"><SocialLinks labels/><a className="location-contact" href="tel:+8801875976488">{profile.phone}</a><span><MapPin size={15}/>{profile.location}</span></div></div></div></section>}
function Footer(){return <footer className="footer"><div className="container footer-inner"><div><a href="#home" className="brand">rubaid<span>.</span></a><span>Rubaid Sharif Mahbub · Flutter Developer</span></div><p>© {new Date().getFullYear()} Rubaid Sharif Mahbub</p><SocialLinks/><a href="#home" className="back-top">Back to top<ArrowUp size={15}/></a></div></footer>}

export default function Portfolio(){const [active,setActive]=useState('home');const progressRef=useRef<HTMLDivElement>(null);useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const revealObserver=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target)}}},{threshold:.08});if(!reduced){document.documentElement.classList.add('motion-ready');document.querySelectorAll('.reveal').forEach(e=>revealObserver.observe(e))}let frame=0;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;if(progressRef.current)progressRef.current.style.transform=`scaleX(${max>0?window.scrollY/max:0})`;let current='home';for(const n of navigation){const element=document.getElementById(n.id);if(element&&element.getBoundingClientRect().top<=180)current=n.id}setActive(current);frame=0};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',scroll,{passive:true});update();return()=>{revealObserver.disconnect();window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);document.documentElement.classList.remove('motion-ready')}},[]);return <><a href="#main-content" className="skip-link">Skip to content</a><div ref={progressRef} className="reading-progress" aria-hidden="true"/><Navigation active={active}/><main id="main-content"><Hero/><SelectedWork/><ExperienceTimeline/><TechnicalExpertise/><About/><Background/><ContactSection/></main><Footer/></>}
